version: "3.6"

services:
  spark-master:
    image: bitnami/spark:2.4.6
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '40400:4040'
      - '48080:8080'
    volumes:
      - './target/scala-2.11/batch-job-lib-assembly-0.1.jar:/home/bitnami/jars/batch-job-lib-assembly-0.1.jar:ro'
      - './src/main/resources/data/:/home/bitnami/data/:ro'

  spark-worker:
    image: bitnami/spark:2.4.6
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '48081:8081'
    volumes:
      - './src/main/resources/data/:/home/bitnami/data/:ro'
    depends_on:
      - spark-master
  db:
    image: bitnami/mongodb:latest
    container_name: mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './src/test/resources/integration_test/:/tmp/query/'
